### ISSUE TITLE
Suggestion: PHP Parallel Lint has a maintained package

### ISSUE THREAD

**Issue by ghost** [DealerDirect/php-qa-tools#39]
Hi,

I think you have been directing developers to a unmaintained package.

Could you update PHP Parallel Lint link to the maintained package.

https://github.com/php-parallel-lint/PHP-Parallel-Lint

**Comment by ghost** [comment]
No news. Close the issue.

**Comment by Potherca** [comment]
To be honest, I don't think this repo is maintained anymore.
