### ISSUE TITLE
Add iniscan ?

### ISSUE THREAD

**Issue by Potherca** [DealerDirect/php-qa-tools#4]
Not entirely sure if this is a good match (less useful on a dev environment and only occasionally needed on a production machine) but https://github.com/psecio/iniscan might be a useful addition.

**Comment by frenck** [comment]
Looks useful to me 👍 

You could test provisioned development environments and/or your custom/own PHP installation.

**Comment by wouteroostervld** [comment]
looks like it doesn't support /etc/php.d/ style config. but that's fixable.

**Comment by frenck** [comment]
@wouteroostervld Well spotted!
Seems like the repository is kinda unmaintained... Could be fun to pick up a fork :)

**Comment by frenck** [comment]
@Potherca This one is open for some time already.

While I really like the idea of this tool, it is kinda unmaintained and even more important: It does not support multi file / dir configurations (which is kinda de default nowadays).

I would like to suggest closing this ticket.

**Comment by frenck** [comment]
As discussed, this is not a tool for the developer, this is more like a "devops" tooling.

Closing this issue for now.
